item { name:'person' id:1 } item { name:'bicycle' id:2 } item { name:'car' id:3 } item { name:'motorcycle' id:4 } item { name:'airplane' id:5 } item { name:'bus' id:6 } item { name:'train' id:7 } item { name:'truck' id:8 } item { name:'bench' id:15 } item { name:'bird' id:16 } item { name:'cat' id:17 } item { name:'dog' id:18 } item { name:'chair' id:62 } item { name:'toilet' id:70 } item { name:'tv' id:72 } item { name:'book' id:84 }